name: CmdOn
version: '${project.version}'
main: com.github.e2318501.cmdon.CmdOn
api-version: '1.19'
author: e2318501
description: Execute commands on the specific event
commands:
  cmdon:
    permission: cmdon.command.cmdon
    usage: |
      /<command> reload
permissions:
  cmdon.command.cmdon:
    default: op
